---
all:
  children:
    zabbix_agents:
      hosts:
        ids-01:
          ansible_host: 192.168.2.242
        TestServer:
          ansible_host: 192.168.2.220
          zabbix_agent_manage_ufw: true
          zabbix_agent_ufw_source: 192.168.2.184
        DietPi:
          ansible_host: 192.168.2.48
    media_hosts:
      hosts:
        media-01:
          ansible_host: 192.168.2.195
