---
zabbix_version: "7.0"
zabbix_agent_package: zabbix-agent2
zabbix_agent_service_name: zabbix-agent2
zabbix_agent_port: 10050
zabbix_agent_hostname: "{{ inventory_hostname }}"
zabbix_agent_server_active: "{{ zabbix_server_address | default('') }}"
