---
all:
  children:
    alloy_hosts:
      hosts:
        app-platform-01:
          ansible_host: 192.168.2.253
          ansible_user: james
          alloy_hostname: app-platform-01
          alloy_host_role: application
          alloy_environment: homelab
          alloy_prometheus_remote_write_url: http://192.168.2.242:9090/api/v1/write
          alloy_loki_write_url: http://192.168.2.242:3100/loki/api/v1/push
