---
all:
  vars:
    ansible_become: false

  children:
    linux_security_hardening:
      hosts:
        zabbix-lxc-01:
          ansible_host: 192.168.2.184
          ansible_user: root
          linux_security_hardening_block_icmp_timestamp: false

    unattended_upgrades:
      hosts:
        zabbix-lxc-01: {}

    alloy_hosts:
      hosts:
        zabbix-lxc-01:
          alloy_hostname: zabbix-lxc-01
          alloy_host_role: zabbix
          alloy_environment: homelab
          alloy_prometheus_remote_write_url: http://192.168.2.242:9090/api/v1/write
          alloy_loki_write_url: http://192.168.2.242:3100/loki/api/v1/push

    postgresql_servers:
      hosts:
        zabbix-lxc-01: {}

    timescaledb_servers:
      hosts:
        zabbix-lxc-01: {}

    nginx_servers:
      hosts:
        zabbix-lxc-01: {}

    zabbix_servers:
      hosts:
        zabbix-lxc-01: {}

    zabbix_agents:
      hosts:
        zabbix-lxc-01: {}
