---
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/proxmox-automation
ansible_become: true
ansible_become_method: sudo

managed_linux_timezone: Europe/London

media_network_primary_interface: eth0
media_network_expected_ipv4: 192.168.2.195
media_network_gateway: 192.168.2.1
media_network_wifi_interface: wlan0
media_network_managed_netplan_file: /etc/netplan/10-media-host-ethernet.yaml
media_network_legacy_ethernet_netplan_file: /etc/netplan/90-NM-75a1216a-9d1a-30cd-8aca-ace5526ec021.yaml
media_network_legacy_wifi_netplan_file: /etc/netplan/90-NM-9ce9ccfd-823b-3512-8ce3-e18405b63bbf.yaml
