all:
  children:
    proxmox_lab:
      hosts:
        debian-iac-test-01:
          ansible_host: 192.168.2.120
          ansible_user: james
          ansible_python_interpreter: /usr/bin/python3.13

    proxmox_hosts:
      hosts:
        PROXMOX:
          ansible_host: 192.168.2.70
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3.13
          ansible_ssh_private_key_file: /home/james/.ssh/proxmox-automation
          ansible_ssh_common_args: '-o IdentitiesOnly=yes'
