---
- name: Baseline Proxmox Debian VM
  hosts: proxmox_lab
  become: true

  tasks:
    - name: Set timezone
      community.general.timezone:
        name: Europe/London

    - name: Install baseline packages
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
          - prometheus-node-exporter
        state: present
        update_cache: true
        install_recommends: false

    - name: Ensure QEMU guest agent is running
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
      when: not ansible_check_mode

    - name: Enable Prometheus node exporter
      ansible.builtin.service:
        name: prometheus-node-exporter
        enabled: true
        state: started
      when: not ansible_check_mode
