---
kodi_user: james
kodi_group: james
kodi_home: /home/james
kodi_service_name: kodi
kodi_display: ':0'
kodi_tty: tty1
kodi_vt: vt1
kodi_restart_sec: 10
kodi_display_manager_service: lightdm.service
kodi_xwrapper_allowed_users: console
kodi_xwrapper_needs_root_rights: 'yes'
kodi_packages:
  - kodi
  - xinit
  - xserver-xorg-core
  - xserver-xorg-input-libinput
  - xserver-xorg-legacy
kodi_conflicting_xorg_packages:
  - xserver-xorg
  - xserver-xorg-video-all
  - xserver-xorg-video-fbdev
